In [1]:
import pandas as pd
import mysql.connector

conn = mysql.connector.connect(
    host='localhost',
    user='root',
    password='hidden*',
    database='anime_data'
)

df_imdb = pd.read_sql('SELECT * FROM imdb WHERE score >= 7 AND votes >= 2000', conn)
df_anime = pd.read_sql("SELECT * FROM anime WHERE genres != '' AND score >= 7 AND ranking <= 3000 AND themes != ''", conn)

conn.close()

C:\Users\sheeh\AppData\Local\Temp\ipykernel_10580\317671224.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_imdb = pd.read_sql('SELECT * FROM imdb WHERE score >= 7 AND votes >= 2000', conn)
C:\Users\sheeh\AppData\Local\Temp\ipykernel_10580\317671224.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_anime = pd.read_sql("SELECT * FROM anime WHERE genres != '' AND score >= 7 AND ranking <= 3000 AND themes != ''", conn)

In [2]:
df_imdb

,title,genre,score,synopsis,votes
0,The Last of Us,"Action, Adventure, Drama",9.1,"After a global pandemic destroys civilization,...",253945
1,The Mandalorian,"Action, Adventure, Fantasy",8.7,The travels of a lone bounty hunter in the out...,506044
2,Outer Banks,"Action, Crime, Drama",7.6,"On an island of haves and have-nots, teen John...",60259
3,1923,"Drama, Western",8.5,The Duttons face a new set of challenges in th...,23136
4,Poker Face,"Crime, Drama, Mystery",8.0,Charlie has an extraordinary ability to determ...,17069
...,...,...,...,...,...
3935,Vruc vetar,Comedy,9.0,"The adventures of Surda, a man in his 30s who ...",2521
3936,The Raikar Case,Thriller,7.1,"An edge-of-the-seat thriller about family, lov...",2586
3937,The Amazing Screw-On Head,"Animation, Action, Adventure",7.7,A Civil War-era secret agent with an extraordi...,2066
3938,Daria in 'Is It Fall Yet?',"Animation, Comedy",8.1,"This animated made-for-TV movie, based on MTV'...",4064
3939,Content Cop,"Comedy, Crime, Talk-Show",8.8,In an effort to bring justice to the YouTube c...,12649

In [3]:
df_anime

,id,mal_id,title,score,rating,genres,themes,demographics,studios,ranking,synopsis
0,1,1,Cowboy Bebop,8.75,R - 17+ (violence & profanity),"Action, Award Winning, Sci-Fi","Adult Cast, Space",,Sunrise,38,"Crime is timeless. By the year 2071, humanity ..."
1,2,5,Cowboy Bebop: Tengoku no Tobira,8.38,R - 17+ (violence & profanity),"Action, Sci-Fi","Adult Cast, Space",,Bones,187,"Another day, another bountyâ€”such is the life o..."
2,3,6,Trigun,8.22,PG-13 - Teens 13 or older,"Action, Adventure, Sci-Fi",Adult Cast,Shounen,Madhouse,326,"Vash the Stampede is the man with a $$60,000,0..."
3,4,7,Witch Hunter Robin,7.25,PG-13 - Teens 13 or older,"Action, Drama, Mystery, Supernatural",Detective,,Sunrise,2843,Robin Sena is a powerful craft user drafted in...
4,6,15,Eyeshield 21,7.92,PG-13 - Teens 13 or older,Sports,Team Sports,Shounen,Gallop,696,"Shy, reserved, and small-statured, Deimon High..."
...,...,...,...,...,...,...,...,...,...,...,...
1659,16588,53236,Road of Naruto,8.52,PG-13 - Teens 13 or older,"Action, Fantasy",Martial Arts,Shounen,Pierrot,121,"In celebration of 20 years of Naruto, Studio P..."
1660,16649,53411,Buddy Daddies,7.75,PG-13 - Teens 13 or older,"Action, Comedy","Childcare, Organized Crime",,P.A. Works,1016,Assassins Kazuki Kurusu and Rei Suwa meet Miri...
1661,16753,53716,Hirogaru Sky! Precure,7.59,G - All Ages,"Action, Fantasy",Mahou Shoujo,,Toei Animation,1411,A major incident in peaceful Skyland?! The inf...
1662,16926,54029,Wu Liuqi: Anying Suming,7.50,R - 17+ (violence & profanity),"Action, Adventure, Comedy, Drama, Mystery","Martial Arts, Super Power",,"Sharefun Studio, AHA Entertainment",1723,The protagonist Wu Liuqi originally lived a ca...
1663,17059,54312,Yuanshen: Hai Dengjie CM Duanpian - Ming Xiao ...,7.43,G - All Ages,Fantasy,"Isekai, Mythology",,,2006,Animated commercial promoting the release of t...

In [4]:
df_anime = df_anime.drop('demographics', axis=1)
df_anime = df_anime.drop('ranking', axis=1)
df_anime = df_anime.drop('studios', axis=1)
df_anime = df_anime.drop('id', axis=1)
df_anime = df_anime.drop('mal_id', axis=1)
df_anime = df_anime.drop('themes', axis=1)
df_anime = df_anime.drop('rating', axis=1)
df_imdb = df_imdb.drop('votes', axis=1)

In [5]:
df_anime

,title,score,genres,synopsis
0,Cowboy Bebop,8.75,"Action, Award Winning, Sci-Fi","Crime is timeless. By the year 2071, humanity ..."
1,Cowboy Bebop: Tengoku no Tobira,8.38,"Action, Sci-Fi","Another day, another bountyâ€”such is the life o..."
2,Trigun,8.22,"Action, Adventure, Sci-Fi","Vash the Stampede is the man with a $$60,000,0..."
3,Witch Hunter Robin,7.25,"Action, Drama, Mystery, Supernatural",Robin Sena is a powerful craft user drafted in...
4,Eyeshield 21,7.92,Sports,"Shy, reserved, and small-statured, Deimon High..."
...,...,...,...,...
1659,Road of Naruto,8.52,"Action, Fantasy","In celebration of 20 years of Naruto, Studio P..."
1660,Buddy Daddies,7.75,"Action, Comedy",Assassins Kazuki Kurusu and Rei Suwa meet Miri...
1661,Hirogaru Sky! Precure,7.59,"Action, Fantasy",A major incident in peaceful Skyland?! The inf...
1662,Wu Liuqi: Anying Suming,7.50,"Action, Adventure, Comedy, Drama, Mystery",The protagonist Wu Liuqi originally lived a ca...
1663,Yuanshen: Hai Dengjie CM Duanpian - Ming Xiao ...,7.43,Fantasy,Animated commercial promoting the release of t...

In [6]:
df_imdb

,title,genre,score,synopsis
0,The Last of Us,"Action, Adventure, Drama",9.1,"After a global pandemic destroys civilization,..."
1,The Mandalorian,"Action, Adventure, Fantasy",8.7,The travels of a lone bounty hunter in the out...
2,Outer Banks,"Action, Crime, Drama",7.6,"On an island of haves and have-nots, teen John..."
3,1923,"Drama, Western",8.5,The Duttons face a new set of challenges in th...
4,Poker Face,"Crime, Drama, Mystery",8.0,Charlie has an extraordinary ability to determ...
...,...,...,...,...
3935,Vruc vetar,Comedy,9.0,"The adventures of Surda, a man in his 30s who ..."
3936,The Raikar Case,Thriller,7.1,"An edge-of-the-seat thriller about family, lov..."
3937,The Amazing Screw-On Head,"Animation, Action, Adventure",7.7,A Civil War-era secret agent with an extraordi...
3938,Daria in 'Is It Fall Yet?',"Animation, Comedy",8.1,"This animated made-for-TV movie, based on MTV'..."
3939,Content Cop,"Comedy, Crime, Talk-Show",8.8,In an effort to bring justice to the YouTube c...

In [15]:
from bs4 import BeautifulSoup
import requests
import json

movie_name = df_imdb['title'].tolist()
n = len(movie_name) // 4
split_lists = [movie_name[i:i+n] for i in range(0, len(movie_name), n)]

list1 = split_lists[0]
list2 = split_lists[1]
list3 = split_lists[2]
list4 = split_lists[3]

storyline = []
# DO NOT EXECUTE OR ELSE STORYLINE WILL RESET AND API CALLS WILL GO TO GARBAGE

In [27]:
API_KEY = '9304cf45'
num_calls = 0
for name in list4:
    url = 'http://www.omdbapi.com/?t=' + name.replace(' ', '+') + '&plot=full' + '&apikey=' + API_KEY + '&'
    response = requests.get(url)
    
    if response.status_code == 200:
        try:
            data = response.json()
            plot = data['Plot']
            storyline.append(plot)
        except KeyError:
            storyline.append('none')
    else:
        storyline.append('none')

In [28]:
num = 0
for name in storyline:
    if name == 'none':
        num += 1
        
num
#replace the none values with their description!!

389

In [30]:
len(storyline)

#add this list to the dataframe and delete the rows with none and remove the synopsis column for the imdb table.

3940

In [31]:
df_imdb['storyline'] = storyline

In [33]:
df_imdb = df_imdb.drop('synopsis', axis=1)
df_imdb

,title,genre,score,storyline
0,The Last of Us,"Action, Adventure, Drama",9.1,Twenty years after modern civilization has bee...
1,The Mandalorian,"Action, Adventure, Fantasy",8.7,"After the stories of Jango and Boba Fett, anot..."
2,Outer Banks,"Action, Crime, Drama",7.6,"On an island of haves and have-nots, teen John..."
3,1923,"Drama, Western",8.5,The Duttons face a new set of challenges in th...
4,Poker Face,"Crime, Drama, Mystery",8.0,Charlie has an extraordinary ability to determ...
...,...,...,...,...
3935,Vruc vetar,Comedy,9.0,"The adventures of Surda, a man in his 30s who ..."
3936,The Raikar Case,Thriller,7.1,set in Goa's Bicholim village in Naik Raikar f...
3937,The Amazing Screw-On Head,"Animation, Action, Adventure",7.7,Unsold animated TV pilot adapted from a short ...
3938,Daria in 'Is It Fall Yet?',"Animation, Comedy",8.1,"From the hit series ""Daria"" comes her first mo..."
3939,Content Cop,"Comedy, Crime, Talk-Show",8.8,"Dark-humored, wise-cracking personality iDubbb..."

In [34]:
df_imdb = df_imdb.rename(columns={'storyline':'synopsis'})
df_imdb

,title,genre,score,synopsis
0,The Last of Us,"Action, Adventure, Drama",9.1,Twenty years after modern civilization has bee...
1,The Mandalorian,"Action, Adventure, Fantasy",8.7,"After the stories of Jango and Boba Fett, anot..."
2,Outer Banks,"Action, Crime, Drama",7.6,"On an island of haves and have-nots, teen John..."
3,1923,"Drama, Western",8.5,The Duttons face a new set of challenges in th...
4,Poker Face,"Crime, Drama, Mystery",8.0,Charlie has an extraordinary ability to determ...
...,...,...,...,...
3935,Vruc vetar,Comedy,9.0,"The adventures of Surda, a man in his 30s who ..."
3936,The Raikar Case,Thriller,7.1,set in Goa's Bicholim village in Naik Raikar f...
3937,The Amazing Screw-On Head,"Animation, Action, Adventure",7.7,Unsold animated TV pilot adapted from a short ...
3938,Daria in 'Is It Fall Yet?',"Animation, Comedy",8.1,"From the hit series ""Daria"" comes her first mo..."
3939,Content Cop,"Comedy, Crime, Talk-Show",8.8,"Dark-humored, wise-cracking personality iDubbb..."

In [35]:
df_imdb = df_imdb.loc[df_imdb['synopsis'] != 'none']
df_imdb

,title,genre,score,synopsis
0,The Last of Us,"Action, Adventure, Drama",9.1,Twenty years after modern civilization has bee...
1,The Mandalorian,"Action, Adventure, Fantasy",8.7,"After the stories of Jango and Boba Fett, anot..."
2,Outer Banks,"Action, Crime, Drama",7.6,"On an island of haves and have-nots, teen John..."
3,1923,"Drama, Western",8.5,The Duttons face a new set of challenges in th...
4,Poker Face,"Crime, Drama, Mystery",8.0,Charlie has an extraordinary ability to determ...
...,...,...,...,...
3935,Vruc vetar,Comedy,9.0,"The adventures of Surda, a man in his 30s who ..."
3936,The Raikar Case,Thriller,7.1,set in Goa's Bicholim village in Naik Raikar f...
3937,The Amazing Screw-On Head,"Animation, Action, Adventure",7.7,Unsold animated TV pilot adapted from a short ...
3938,Daria in 'Is It Fall Yet?',"Animation, Comedy",8.1,"From the hit series ""Daria"" comes her first mo..."
3939,Content Cop,"Comedy, Crime, Talk-Show",8.8,"Dark-humored, wise-cracking personality iDubbb..."

In [44]:
df_imdb.to_csv('df_imdb.csv', index=False)

In [36]:
df_anime

,title,score,genres,synopsis
0,Cowboy Bebop,8.75,"Action, Award Winning, Sci-Fi","Crime is timeless. By the year 2071, humanity ..."
1,Cowboy Bebop: Tengoku no Tobira,8.38,"Action, Sci-Fi","Another day, another bountyâ€”such is the life o..."
2,Trigun,8.22,"Action, Adventure, Sci-Fi","Vash the Stampede is the man with a $$60,000,0..."
3,Witch Hunter Robin,7.25,"Action, Drama, Mystery, Supernatural",Robin Sena is a powerful craft user drafted in...
4,Eyeshield 21,7.92,Sports,"Shy, reserved, and small-statured, Deimon High..."
...,...,...,...,...
1659,Road of Naruto,8.52,"Action, Fantasy","In celebration of 20 years of Naruto, Studio P..."
1660,Buddy Daddies,7.75,"Action, Comedy",Assassins Kazuki Kurusu and Rei Suwa meet Miri...
1661,Hirogaru Sky! Precure,7.59,"Action, Fantasy",A major incident in peaceful Skyland?! The inf...
1662,Wu Liuqi: Anying Suming,7.50,"Action, Adventure, Comedy, Drama, Mystery",The protagonist Wu Liuqi originally lived a ca...
1663,Yuanshen: Hai Dengjie CM Duanpian - Ming Xiao ...,7.43,Fantasy,Animated commercial promoting the release of t...

In [37]:
df_anime = df_anime[['title', 'genres', 'score', 'synopsis']]
df_anime.rename(columns={'genres': 'genre'}, inplace=True)

df = pd.concat([df_anime, df_imdb], axis=0)

In [38]:
df

,title,genre,score,synopsis
0,Cowboy Bebop,"Action, Award Winning, Sci-Fi",8.75,"Crime is timeless. By the year 2071, humanity ..."
1,Cowboy Bebop: Tengoku no Tobira,"Action, Sci-Fi",8.38,"Another day, another bountyâ€”such is the life o..."
2,Trigun,"Action, Adventure, Sci-Fi",8.22,"Vash the Stampede is the man with a $$60,000,0..."
3,Witch Hunter Robin,"Action, Drama, Mystery, Supernatural",7.25,Robin Sena is a powerful craft user drafted in...
4,Eyeshield 21,Sports,7.92,"Shy, reserved, and small-statured, Deimon High..."
...,...,...,...,...
3935,Vruc vetar,Comedy,9.00,"The adventures of Surda, a man in his 30s who ..."
3936,The Raikar Case,Thriller,7.10,set in Goa's Bicholim village in Naik Raikar f...
3937,The Amazing Screw-On Head,"Animation, Action, Adventure",7.70,Unsold animated TV pilot adapted from a short ...
3938,Daria in 'Is It Fall Yet?',"Animation, Comedy",8.10,"From the hit series ""Daria"" comes her first mo..."
3939,Content Cop,"Comedy, Crime, Talk-Show",8.80,"Dark-humored, wise-cracking personality iDubbb..."

In [39]:
dummy_genres = df['genre'].str.get_dummies(sep=', ')
df = pd.concat([df, dummy_genres], axis=1)
df.drop('genre', axis=1, inplace=True)

df

,title,score,synopsis,Action,Adventure,Animation,Avant Garde,Award Winning,Biography,Boys Love,...,Short,Slice of Life,Sport,Sports,Supernatural,Suspense,Talk-Show,Thriller,War,Western
0,Cowboy Bebop,8.75,"Crime is timeless. By the year 2071, humanity ...",1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Cowboy Bebop: Tengoku no Tobira,8.38,"Another day, another bountyâ€”such is the life o...",1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Trigun,8.22,"Vash the Stampede is the man with a $$60,000,0...",1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Witch Hunter Robin,7.25,Robin Sena is a powerful craft user drafted in...,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,Eyeshield 21,7.92,"Shy, reserved, and small-statured, Deimon High...",0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3935,Vruc vetar,9.00,"The adventures of Surda, a man in his 30s who ...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3936,The Raikar Case,7.10,set in Goa's Bicholim village in Naik Raikar f...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3937,The Amazing Screw-On Head,7.70,Unsold animated TV pilot adapted from a short ...,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3938,Daria in 'Is It Fall Yet?',8.10,"From the hit series ""Daria"" comes her first mo...",0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3939,Content Cop,8.80,"Dark-humored, wise-cracking personality iDubbb...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [40]:
df.isnull().sum()

title            0
score            0
synopsis         7
Action           0
Adventure        0
Animation        0
Avant Garde      0
Award Winning    0
Biography        0
Boys Love        0
Comedy           0
Crime            0
Documentary      0
Drama            0
Ecchi            0
Family           0
Fantasy          0
Game-Show        0
Girls Love       0
Gourmet          0
History          0
Horror           0
Music            0
Musical          0
Mystery          0
News             0
Reality-TV       0
Romance          0
Sci-Fi           0
Short            0
Slice of Life    0
Sport            0
Sports           0
Supernatural     0
Suspense         0
Talk-Show        0
Thriller         0
War              0
Western          0
dtype: int64

In [101]:
df = df.dropna()
df.isnull().sum()

title            0
score            0
synopsis         0
Action           0
Adventure        0
Animation        0
Avant Garde      0
Award Winning    0
Biography        0
Boys Love        0
Comedy           0
Crime            0
Documentary      0
Drama            0
Ecchi            0
Family           0
Fantasy          0
Game-Show        0
Girls Love       0
Gourmet          0
History          0
Horror           0
Music            0
Musical          0
Mystery          0
News             0
Reality-TV       0
Romance          0
Sci-Fi           0
Short            0
Slice of Life    0
Sport            0
Sports           0
Supernatural     0
Suspense         0
Talk-Show        0
Thriller         0
War              0
Western          0
dtype: int64

In [102]:
genre_df = df.drop(['title', 'score', 'synopsis'], axis=1)
text_df = df[['synopsis']]
title_df = df[['title']]

In [103]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')

stop_words = set(stopwords.words('english'))
def remove_stop_words(text):
    words = word_tokenize(text)
    filtered_words = [word for word in words if word.lower() not in stop_words]
    filtered_text = ' '.join(filtered_words)
    return filtered_text

text_df['synopsis'] = text_df['synopsis'].apply(remove_stop_words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sheeh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sheeh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
C:\Users\sheeh\AppData\Local\Temp\ipykernel_10580\2777155791.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text_df['synopsis'] = text_df['synopsis'].apply(remove_stop_words)

In [104]:
df['synopsis'] = text_df[['synopsis']]

In [105]:
df

,title,score,synopsis,Action,Adventure,Animation,Avant Garde,Award Winning,Biography,Boys Love,...,Short,Slice of Life,Sport,Sports,Supernatural,Suspense,Talk-Show,Thriller,War,Western
0,Cowboy Bebop,8.75,"Crime timeless . year 2071 , humanity expanded...",1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Cowboy Bebop: Tengoku no Tobira,8.38,"Another day , another bountyâ€”such life often u...",1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Trigun,8.22,"Vash Stampede man $ $ 60,000,000,000 bounty he...",1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Witch Hunter Robin,7.25,Robin Sena powerful craft user drafted STNJâ€”a ...,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,Eyeshield 21,7.92,"Shy , reserved , small-statured , Deimon High ...",0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3935,Vruc vetar,9.00,"adventures Surda , man 30s comes small town Be...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3936,The Raikar Case,7.10,set Goa 's Bicholim village Naik Raikar family...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3937,The Amazing Screw-On Head,7.70,Unsold animated TV pilot adapted short comic b...,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3938,Daria in 'Is It Fall Yet?',8.10,"hit series `` Daria `` comes first movie , `` ...",0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3939,Content Cop,8.80,"Dark-humored , wise-cracking personality iDubb...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [106]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

vectorize_df = df.drop(['title', 'score'], axis=1)
genre_array = np.array(vectorize_df.iloc[:, 1:])
vectorizer = CountVectorizer()
synopsis_vectors = vectorizer.fit_transform(vectorize_df['synopsis'])

In [107]:
combined_array = np.concatenate([synopsis_vectors.toarray(), genre_array], axis=1)
feature_names = list(vectorizer.vocabulary_.keys()) + list(vectorize_df.columns[1:])
vectorized_df = pd.DataFrame(combined_array, columns=feature_names)

In [108]:
vectorized_df

,crime,timeless,year,2071,humanity,expanded,across,galaxy,filling,surface,...,Short,Slice of Life,Sport,Sports,Supernatural,Suspense,Talk-Show,Thriller,War,Western
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3961,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3962,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3963,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3964,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3965,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [109]:
df_test = df.copy()
df_test.drop(index=df_test.index, inplace=True)
df_test

Empty DataFrame
Columns: [title, score, synopsis, Action, Adventure, Animation, Avant Garde, Award Winning, Biography, Boys Love, Comedy, Crime, Documentary, Drama, Ecchi, Family, Fantasy, Game-Show, Girls Love, Gourmet, History, Horror, Music, Musical, Mystery, News, Reality-TV, Romance, Sci-Fi, Short, Slice of Life, Sport, Sports, Supernatural, Suspense, Talk-Show, Thriller, War, Western]
Index: []

[0 rows x 39 columns]

In [110]:
column_list = df_test.columns.tolist()

In [111]:
user_dict = {key: 0 for key in column_list}

In [182]:
def update_dict(d, l):
    for k in d:
        if k in l:
            d[k] = 1
    return d

update_dict(user_dict, ['Drama', 'Sci-Fi', 'Suspense'])

{'title': 'Steins;Gate',
 'score': 9.5,
 'synopsis': '\nEccentric scientist Rintarou Okabe has a never-ending thirst for scientific exploration. Together with his ditzy but well-meaning friend Mayuri Shiina and his roommate Itaru Hashida, Rintarou founds the Future Gadget Laboratory in the hopes of creating technological innovations that baffle the human psyche. Despite claims of grandeur, the only notable "gadget" the trio have created is a microwave that has the mystifying power to turn bananas into green goo.\n\nHowever, when Rintarou decides to attend neuroscientist Kurisu Makise\'s conference on time travel, he experiences a series of strange events that lead him to believe that there is more to the "Phone Microwave" gadget than meets the eye. Apparently able to send text messages into the past using the microwave, Rintarou dabbles further with the "time machine," attracting the ire and attention of the mysterious organization SERN.\n\nDue to the novel discovery, Rintarou and his friends find themselves in an ever-present danger. As he works to mitigate the damage his invention has caused to the timeline, he is not only fighting a battle to save his loved ones, but also one against his degrading sanity.\n',
 'Action': 0,
 'Adventure': 0,
 'Animation': 0,
 'Avant Garde': 0,
 'Award Winning': 0,
 'Biography': 1,
 'Boys Love': 0,
 'Comedy': 0,
 'Crime': 0,
 'Documentary': 0,
 'Drama': 1,
 'Ecchi': 0,
 'Family': 0,
 'Fantasy': 0,
 'Game-Show': 0,
 'Girls Love': 0,
 'Gourmet': 0,
 'History': 0,
 'Horror': 0,
 'Music': 0,
 'Musical': 0,
 'Mystery': 0,
 'News': 0,
 'Reality-TV': 0,
 'Romance': 0,
 'Sci-Fi': 1,
 'Short': 0,
 'Slice of Life': 0,
 'Sport': 0,
 'Sports': 0,
 'Supernatural': 0,
 'Suspense': 1,
 'Talk-Show': 0,
 'Thriller': 0,
 'War': 0,
 'Western': 0}

In [231]:
user_dict['title'] = 'Steins;gate'
user_dict['score'] = 9.5
user_dict['synopsis'] = '''
Eccentric scientist Rintarou Okabe has a never-ending thirst for scientific exploration. Together with his ditzy but well-meaning friend Mayuri Shiina and his roommate Itaru Hashida, Rintarou founds the Future Gadget Laboratory in the hopes of creating technological innovations that baffle the human psyche. Despite claims of grandeur, the only notable "gadget" the trio have created is a microwave that has the mystifying power to turn bananas into green goo.

However, when Rintarou decides to attend neuroscientist Kurisu Makise's conference on time travel, he experiences a series of strange events that lead him to believe that there is more to the "Phone Microwave" gadget than meets the eye. Apparently able to send text messages into the past using the microwave, Rintarou dabbles further with the "time machine," attracting the ire and attention of the mysterious organization SERN.

Due to the novel discovery, Rintarou and his friends find themselves in an ever-present danger. As he works to mitigate the damage his invention has caused to the timeline, he is not only fighting a battle to save his loved ones, but also one against his degrading sanity.
'''

In [232]:
user_df = pd.DataFrame(user_dict, index=[0])

In [233]:
user_df

,title,score,synopsis,Action,Adventure,Animation,Avant Garde,Award Winning,Biography,Boys Love,...,Short,Slice of Life,Sport,Sports,Supernatural,Suspense,Talk-Show,Thriller,War,Western
0,Steins;gate,9.5,\nEccentric scientist Rintarou Okabe has a nev...,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0

In [234]:
user_df['synopsis'] = user_df['synopsis'].apply(remove_stop_words)

In [235]:
user_df

,title,score,synopsis,Action,Adventure,Animation,Avant Garde,Award Winning,Biography,Boys Love,...,Short,Slice of Life,Sport,Sports,Supernatural,Suspense,Talk-Show,Thriller,War,Western
0,Steins;gate,9.5,Eccentric scientist Rintarou Okabe never-endin...,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0

In [236]:
synopsis_vectors_user = vectorizer.transform(user_df['synopsis'])
genre_user_array = user_df.iloc[:, 3:].values

In [237]:
combined_array_user = np.concatenate([synopsis_vectors_user.toarray(), genre_user_array], axis=1)

In [238]:
feature_names_user = list(vectorizer.vocabulary_.keys()) + list(user_df.columns[3:])
vectorized_df_user = pd.DataFrame(combined_array_user, columns=feature_names_user)

In [239]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarities = cosine_similarity(vectorized_df_user, vectorized_df)

In [240]:
cosine_similarities

array([[0.02135245, 0.03319188, 0.04501491, ..., 0.02477394, 0.01280552,
        0.        ]])

In [241]:
sorted_indices = np.argsort(cosine_similarities[0])[::-1]

In [242]:
top_5_indices = sorted_indices[:15]

In [243]:
top_5_indices

array([2124,  804,  761,  548, 1767, 1488, 3644, 3600,  274, 3103, 1829,
       2441, 3036, 2916, 1091], dtype=int64)

In [244]:
name = []
for index in top_5_indices:
    name.append(df.iloc[index]['title'])

movie_title = user_df['title'][0]
new_name = [word for word in name if movie_title.lower() not in word.lower()]

In [245]:
new_name

['Timeless',
 'Doctor Who',
 'The Song of Lunch',
 'Odyssey 5',
 'Toki wo Kakeru Shoujo',
 'Doctor Who',
 'Paper Girls',
 'Seven Days',
 'Phil of the Future',
 'Xiao Lu He Xiao Lan']

In [71]:
df.to_csv('df.csv', index=False)

In [165]:
count = (df['synopsis'].str.len() <= 150).sum()
count

16

In [77]:
df = df[df['synopsis'].str.len() >= 150]

In [98]:
df

,title,score,synopsis,Action,Adventure,Animation,Avant Garde,Award Winning,Biography,Boys Love,...,Short,Slice of Life,Sport,Sports,Supernatural,Suspense,Talk-Show,Thriller,War,Western
0,Cowboy Bebop,8.75,"Crime timeless . year 2071 , humanity expanded...",1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Cowboy Bebop: Tengoku no Tobira,8.38,"Another day , another bountyâ€”such life often u...",1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Trigun,8.22,"Vash Stampede man $ $ 60,000,000,000 bounty he...",1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Witch Hunter Robin,7.25,Robin Sena powerful craft user drafted STNJâ€”a ...,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,Eyeshield 21,7.92,"Shy , reserved , small-statured , Deimon High ...",0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3935,Vruc vetar,9.00,"adventures Surda , man 30s comes small town Be...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3936,The Raikar Case,7.10,set Goa 's Bicholim village Naik Raikar family...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3937,The Amazing Screw-On Head,7.70,Unsold animated TV pilot adapted short comic b...,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3938,Daria in 'Is It Fall Yet?',8.10,"hit series `` Daria '' comes first movie , `` ...",0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3939,Content Cop,8.80,"Dark-humored , wise-cracking personality iDubb...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [262]:
!pip install --no-cache-dir jikanpy-v4

Requirement already satisfied: jikanpy-v4 in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (1.0.1)
Requirement already satisfied: requests in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from jikanpy-v4) (2.28.1)
Requirement already satisfied: simplejson in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from jikanpy-v4) (3.18.3)
Requirement already satisfied: aiohttp in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from jikanpy-v4) (3.8.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->jikanpy-v4) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->jikanpy-v4) (1.3.3)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->jikanpy-v4) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->jikanpy-v4) (1.8.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->jikanpy-v4) (22.2.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->jikanpy-v4) (1.3.1)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->jikanpy-v4) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from requests->jikanpy-v4) (1.26.13)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from requests->jikanpy-v4) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sheeh\appdata\local\programs\python\python310\lib\site-packages (from requests->jikanpy-v4) (2022.12.7)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip